# Generated by Django 6.0.2 on 2026-05-23 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterField(
            model_name='women',
            name='content',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Текст статьи'),
        ),
    ]
